// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzsPX3qSPsemVyFpOHu9-0VMGOBNyEzXM',
    appId: '1:1002701264389:web:300606122aa4521eebee6c',
    messagingSenderId: '1002701264389',
    projectId: 'flutter-firebase-dersler-e4130',
    authDomain: 'flutter-firebase-dersler-e4130.firebaseapp.com',
    storageBucket: 'flutter-firebase-dersler-e4130.appspot.com',
    measurementId: 'G-Z281GHSYPZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqQhW4DDzMgHBe8k6K3wCJvT3RVBZt4ZA',
    appId: '1:1002701264389:android:a8a3ebf0939b9f15ebee6c',
    messagingSenderId: '1002701264389',
    projectId: 'flutter-firebase-dersler-e4130',
    storageBucket: 'flutter-firebase-dersler-e4130.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDD78rfAQZXWyLbRry1Pf80BcE1qohsyos',
    appId: '1:1002701264389:ios:88b7df6a953976c3ebee6c',
    messagingSenderId: '1002701264389',
    projectId: 'flutter-firebase-dersler-e4130',
    storageBucket: 'flutter-firebase-dersler-e4130.appspot.com',
    iosClientId: '1002701264389-gbmblhu2jlrk2fonqus606tk3nikmapi.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterWhatsappClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDD78rfAQZXWyLbRry1Pf80BcE1qohsyos',
    appId: '1:1002701264389:ios:88b7df6a953976c3ebee6c',
    messagingSenderId: '1002701264389',
    projectId: 'flutter-firebase-dersler-e4130',
    storageBucket: 'flutter-firebase-dersler-e4130.appspot.com',
    iosClientId: '1002701264389-gbmblhu2jlrk2fonqus606tk3nikmapi.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterWhatsappClone',
  );
}

// Platform  Firebase App Id
// web       1:1002701264389:web:300606122aa4521eebee6c
// android   1:1002701264389:android:a8a3ebf0939b9f15ebee6c
// ios       1:1002701264389:ios:88b7df6a953976c3ebee6c
// macos     1:1002701264389:ios:88b7df6a953976c3ebee6c