// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxsmTxg3RhL3oM7YVbMgtK73X3Hk0ENAc',
    appId: '1:975839031218:web:96b2cc00bdc1343104beab',
    messagingSenderId: '975839031218',
    projectId: 'flutter-whatsapp-clone-3d171',
    authDomain: 'flutter-whatsapp-clone-3d171.firebaseapp.com',
    databaseURL: 'https://flutter-whatsapp-clone-3d171-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-whatsapp-clone-3d171.appspot.com',
    measurementId: 'G-M6GZE6K25E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClf9kBvIh2jLo94zVz7Ifhbpurbjx-18s',
    appId: '1:975839031218:android:40c815a14af6fdff04beab',
    messagingSenderId: '975839031218',
    projectId: 'flutter-whatsapp-clone-3d171',
    databaseURL: 'https://flutter-whatsapp-clone-3d171-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-whatsapp-clone-3d171.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUxZSOESwiL9jTyjHvajMi9HkdfWTQNAU',
    appId: '1:975839031218:ios:af9972dfafa2d8fc04beab',
    messagingSenderId: '975839031218',
    projectId: 'flutter-whatsapp-clone-3d171',
    databaseURL: 'https://flutter-whatsapp-clone-3d171-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-whatsapp-clone-3d171.appspot.com',
    androidClientId: '975839031218-hj4oh6v41g6l8m7i6ppgng5pod0dpe97.apps.googleusercontent.com',
    iosClientId: '975839031218-c985jfboa7js0il9krp513kifuum74nn.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterWhatsappClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUxZSOESwiL9jTyjHvajMi9HkdfWTQNAU',
    appId: '1:975839031218:ios:af9972dfafa2d8fc04beab',
    messagingSenderId: '975839031218',
    projectId: 'flutter-whatsapp-clone-3d171',
    databaseURL: 'https://flutter-whatsapp-clone-3d171-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-whatsapp-clone-3d171.appspot.com',
    androidClientId: '975839031218-hj4oh6v41g6l8m7i6ppgng5pod0dpe97.apps.googleusercontent.com',
    iosClientId: '975839031218-c985jfboa7js0il9krp513kifuum74nn.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterWhatsappClone',
  );
}
